export const STATUS_CODES = {

    // Success
    OK: 200,
    CREATED: 201,
    NO_CONTENT: 204,

    // Client Errors
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,

    // Server Errors
    INTERNAL_SERVER_ERROR: 500
};

export const MESSAGES = {
    TOO_MANY_REQUESTS: "Too many requests. Please try again later.",
    TOO_MANY_LOGIN_REQUESTS: "Too many login requests. Please try again later.",
    TOO_MANY_OTP_REQUESTS: "Too many Otp requests. Please try again later.",

    API_RUNNING: "ShopCart API is running",
    VALIDATION_FAILED: "Validation failed",
    AUTHENTICATION_REQUIRED: "Authentication required",
    ACCESS_DENIED: "Access denied",
    OTP_SENT: "OTP sent successfully",
    LOGIN_SUCCESSFUL: "Login successful",
    AUTHENTICATION_REQUIRED: "Authentication required",
    SELLER_OTP_SENT: "Seller OTP sent successfully",
    SELLER_LOGIN_SUCCESSFUL: "Seller login successful",
    INVALID_TOKEN: "Invalid or expired token",
    CATEGORY_CREATED: "Category created successfully",
    CATEGORIES_FETCHED: "Categories fetched successfully",
    CATEGORY_UPDATED: "Category updated successfully",
    CATEGORY_DELETED: "Category deleted successfully",

    ADDRESS_CREATED:"Address created successfully",
    ADDRESS_FETCHED:"Addresses fetched successfully",
    ADDRESS_NOT_FOUND:"Address not found",
    ADDRESS_UPDATED:"Address updated successfully",
    ADDRESS_DELETED:"Address deleted successfully",
    DEFAULT_ADDRESS_UPDATED:"Default address updated successfully",
    ATTRIBUTE_CREATED:"Attribute created successfully",
    ATTRIBUTE_FETCHED:"Attributes fetched successfully",
    ATTRIBUTE_UPDATED:"Attribute updated successfully",
    ATTRIBUTE_DELETED:"Attribute deleted successfully",
    ATTRIBUTE_VALUE_CREATED:"Attribute value created successfully",
    ATTRIBUTE_VALUE_FETCHED:"Attribute values fetched successfully",
    ATTRIBUTE_VALUE_UPDATED:"Attribute value updated successfully",
    ATTRIBUTE_VALUE_DELETED:"Attribute value deleted successfully",

    INVENTORY_FETCHED:"Inventory fetched successfully",
    INVENTORY_UPDATED:"Inventory updated successfully",
    PRODUCT_CREATED:"Product created successfully",
    PRODUCT_FETCHED:"Product fetched successfully",
    PRODUCT_UPDATED:"Product updated successfully",
    PRODUCT_DELETED:"Product deleted successfully",
    PRODUCT_IMAGE_ADDED:"Product image added successfully",
    PRODUCT_IMAGES_FETCHED:"Product images fetched successfully",
    PRODUCT_IMAGE_UPDATED:"Product image updated successfully",
    PRODUCT_IMAGE_DELETED:"Product Image deleted successfully",
    PRODUCT_VARIANT_CREATED:"Product variant created successfully",
    PRODUCT_VARIANTS_FETCHED:"Product variants fetched successfully",
    PRODUCT_VARIANT_UPDATED:"Product variant updated successfully",
    PRODUCT_VARIANT_DELETED:"Product variant deleted successfully",
    ITEM_ADDED_TO_CART:"Item added to cart successfully",
    CART_FETCHED:"Cart fetched successfully",
    CART_ITEM_UPDATED:"Cart item updated successfully",
    CART_ITEM_REMOVED:"Cart item removed successfully",
    CART_CLEARED:"Cart cleared successfully",
    ORDER_PLACED:"Order placed successfully",
    ORDER_STATUS_UPDATED: "Order Status updated successfully",

    PAYMENT_FETCHED:"Payments fetched successfully",
    PAYMENT_METHOD_ADDED:"Payment method added successfully",
    PAYMENT_METHOD_FETCHED:"Payment methods fetched successfully",
    PAYMENT_METHOD_DELETED:"Payment method deleted successfully",
    DEFAULT_PAYMENT_METHOD_UPDATED:"Default payment method updated successfully",
    PAYMENT_CREATED:"Payment created successfully",

    WISHLIST_ITEM_ADDED:"WishList item added successfully",
    WISHLIST_FETCHED:"WishList item fetched successfully",
    WISHLIST_ITEM_REMOVED:"WishList item removed successfully",

    ORDER_STATUS_HISTORY_FETCHED:"Order status history fetched.",
    NOTIFICATION_CREATED:"Notification created successfully",
    NOTIFICATION_FETCHED:"Notifications fetched successfully",
    UNREAD_NOTIFICATION_COUNT_FETCHED:"Unread notification count fetched successfully",
    NOTIFICATION_MARKED_AS_READ:"Notification marked as read successfully",
    ALL_NOTIFICATION_MARKED_AS_READ:"All notifications marked as read successfully",
    NOTIFICATION_DELETED:"Notification deleted successfully",
    RETURN_REQUEST_CREATED:"Return request created successfully",
    RETURNS_FETCHED:"Returns fetched Successfully",
    RETURN_DETAIL_FETCHED:"Return detail Fetched Successfully",
    RETURN_APPROVED:"Return Approved Successfully",
    RETURN_REJECTED:"Return Rejected Successfully",
    RETURN_MARKED_AS_PICKED_UP:"Return marked as picked up successfully",
    RETURN_MARKED_AS_RECEIVED:"Return marked as received successfully",
    RETURNED_CANCELLED:"Returned cancelled successfully",
    PRODUCT_ADDED_TO_CART:"Product added to cart successfully",
    REVIEW_CREATED:"Review created successfully",
    REVIEWS_FETCHED:"Reviews fetched successfully",
    REVIEW_FETCHED:"Review fetched successfully",
    REVIEW_UPDATED:"Review updated successfully",
    REVIEW_DELETED:"Review deleted successfully",

    COUPON_CREATED:"Coupon created successfully",
    COUPONS_FETCHED:"Coupons fetched successfully",
    COUPON_FETCHED:"Coupon fetched successfully",
    COUPON_UPDATED:"Coupon updated successfully",
    COUPON_DELETED:"Coupon deleted successfully",
    COUPON_APPLIED:"Coupon applied successfully",

};